"""Initial migration

Revision ID: 22ad148351b5
Revises: 909c395418c7
Create Date: 2025-05-09 12:24:17.315766

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '22ad148351b5'
down_revision = '909c395418c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 