"""Initial migration

Revision ID: 5f18af0c68f5
Revises: 8f00b407f3e9
Create Date: 2025-05-09 12:34:28.315269

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5f18af0c68f5'
down_revision = '8f00b407f3e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 