"""Initial migration

Revision ID: 8aae5f120513
Revises: 22ad148351b5
Create Date: 2025-05-09 12:32:34.710628

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8aae5f120513'
down_revision = '22ad148351b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 