"""Initial migration

Revision ID: 8f00b407f3e9
Revises: 8aae5f120513
Create Date: 2025-05-09 12:33:12.329114

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8f00b407f3e9'
down_revision = '8aae5f120513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 