"""Initial migration

Revision ID: 909c395418c7
Revises: cfa42e4f868d
Create Date: 2025-05-09 12:24:05.046481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '909c395418c7'
down_revision = 'cfa42e4f868d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 