"""Initial migration

Revision ID: cfa42e4f868d
Revises: a78138bf2d25
Create Date: 2025-05-09 12:23:01.191932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cfa42e4f868d'
down_revision = 'a78138bf2d25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 